;************************************************************************************************
;*                                                                                              *
;*      Equates.inc:                                                                            *
;*                                                                                              *
;*      Hier können verschiedene Equates eingefügt werden                                       *
;*                                                                                              *
;************************************************************************************************


;well lets try it


;TODO:

;	how do pointers to a position of a variable work?

;	use them in Blinklicht to point at the right position 
;	on the lcd

;	Tastenklick may not work. delete bset and make comments above to code